version: '3.1'

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: employees
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    networks:
      - lw-employees
    volumes:
      - $PWD/mysql-entrypoint:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - lw-employees

networks:
  lw-employees: