version: '3.1'

services:
  api:
    image: ruby:2.5
    environment:
      LC_ALL: C.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    ports:
      - 9292:9292
    networks:
      - lw-employees
    volumes:
      - $PWD:/usr/src/app
    working_dir: /usr/src/app
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: employees
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    networks:
      - lw-employees
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql-entrypoint:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - lw-employees

networks:
  lw-employees: