version: '3.4'

services:
  app:
    build:
      context: .
      target: builder
    environment:
      LC_ALL: C.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      EMP_HOST: db
      EMP_DATABASE: employees
      EMP_USERNAME: db
      EMP_PASSWORD: db
    depends_on:
      - db
    ports:
      - 9292:9292
    networks:
      - lw-employees
    volumes:
      - $PWD:/usr/src/app
    working_dir: /usr/src/app/employeesdb
  employeesdb:
    build: .
    depends_on:
      - db
    networks:
      - lw-employees
    environment:
      LC_ALL: C.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      EMP_HOST: db
      EMP_DATABASE: employees
      EMP_USERNAME: db
      EMP_PASSWORD: db
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: employees
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    networks:
      - lw-employees
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql-entrypoint:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - lw-employees

networks:
  lw-employees:
